Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.3"

  config.vm.network "private_network", ip: "192.168.33.101"

  config.vm.provision "shell", path: "shell/up.sh"

  config.vm.synced_folder "../../", "/usr/share/nginx/html", \
    :create => true, \
    :owner  => 'vagrant', \
    :group  => 'vagrant', \
    :mount_options => ['dmode=755,fmode=755']

  config.vm.synced_folder "../../storage", "/usr/share/nginx/html/storage", \
    :create => true, \
    :owner  => 'vagrant', \
    :group  => 'vagrant', \
    :mount_options => ['dmode=777,fmode=777']
end
